Feature: Branch protection rule
QuesDevTeam/Git-Convention pull request #31
Opened 2023-10-14 01:53 UTC by crowjdh

Resolves #13

## 작업 배경
- https://github.com/QuesDevTeam/Git-Convention/discussions/25
- 통일되지 않은 branch protection rule 산재로 인한 협업 속도 저하
- Force push로 인한 리뷰 코스트 증대

## 작업 내용
- Branch 보호 및 batch update 규칙 추가
- Force push 규칙 추가

2023-10-15 04:24 UTC, dongjuny requested changes

2023-10-15 04:24 UTC, dongjuny commented on branch/BRANCHING.md
해당 파일의 내용이 마지막 PR #29 내용이랑 일치하지 않는거 같습니다.!

2023-10-15 07:17 UTC, crowjdh commented on branch/BRANCHING.md
!? 작업 중에 머지가 됐나 보네요 ㅠ 정리해서 새로 푸시겠습니다 :)

2023-10-16 00:35 UTC, iinnu commented on branch/PROTECTION.md
> +  - PR 범위 내에서 resolve할 수 없는 conversation은 `issuel 혹은 discussion으로 이동`합니다
`issuel 혹은 discussion으로 이동` 부분에서 `issue`로 수정되면 좋을 것 같습니다 😁

2023-10-16 02:42 UTC, yeareater submitted a review, later dismissed

2023-10-16 02:42 UTC, yeareater commented on pr/README.md
> +> PR 사이즈가 충분히 작다면 force push를 하기 위한 부담도 작아집니다. 특별 규칙을 고려하기 전에 기본 규칙을 잘 지키도록 합니다.
👍🏼

2023-10-16 04:06 UTC, dongjuny submitted a review, later dismissed
🤗

2023-10-16 04:09 UTC, biio-front approved these changes
:)

2023-10-16 07:03 UTC, crowjdh commented on branch/PROTECTION.md
> +  - PR 범위 내에서 resolve할 수 없는 conversation은 `issuel 혹은 discussion으로 이동`합니다
아 순간 무슨 말씀인가 했네요 ㅋㅋ 네 수정하겠습니다 잘 읽어봐주셔서 감사합니다!

2023-10-16 08:49 UTC, yeareater approved these changes

2023-10-16 08:51 UTC, biio-front approved these changes

2023-10-16 09:06 UTC, DonghyunNa approved these changes
고생하셨습니다 👍

2023-10-17 01:31 UTC, dongjuny approved these changes

2023-10-17 02:32 UTC, iinnu approved these changes
:)

2023-10-17 07:56 UTC, merged